### ISSUE TITLE
MagicMirror v2

### ISSUE THREAD

**Issue by CFenner** [Vaggan/MagicMirror-SonosModule#1]
Hi,

as I stated [here](https://github.com/MichMich/MagicMirror/issues/94#issuecomment-201941065) I migrated your module to the new module system. Shall I try to merge it in this repo?

**Comment by Vaggan** [comment]
Hi,

Yes, I would appreciate that.
Can you merge to the "MagicMirror2" branch?

I still need the old version to work for a while longer.

**Comment by CFenner** [comment]
Ok, I'll try tonight.

You could move the old stuff to a v1.0 branch and do a release tag.
